name: Autoversion

on:
  schedule:
    - cron: '0 0 * * 1'
  workflow_dispatch:

jobs:
  bump:
    runs-on: ubuntu-slim
    steps:
      - uses: plengauer/opentelemetry-github/actions/instrument/job@v5.42.2
        env:
          OTEL_EXPORTER_OTLP_ENDPOINT: ${{ secrets.OTEL_EXPORTER_OTLP_ENDPOINT }}
          OTEL_EXPORTER_OTLP_HEADERS: ${{ secrets.OTEL_EXPORTER_OTLP_HEADERS }}
        with:
          secrets_to_redact: |-
            ${{ github.token }}
            ${{ secrets.ACTIONS_GITHUB_TOKEN }}
            ${{ secrets.OPENAI_TOKEN }}
      - uses: plengauer/autoversion@v2.3.0
        with:
          github_token: ${{ secrets.ACTIONS_GITHUB_TOKEN }}
          openai_token: ${{ secrets.OPENAI_TOKEN }}
    permissions:
      actions: read
